id: AE5ED3241
title: Prayer for the Swift Rebirth of Dodrupchen Rinpoche
type: translation
pechas:
- I2CE4ECEA
- I13597697
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:54:18.330400
  last_modified_at: 2023-01-04 11:54:18.330412
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I2CE4ECEA/A634: '1779'
  I13597697/4248: '1779'
